from __future__ import annotations

import os
from uuid import UUID, uuid4

import pytest

os.environ.setdefault(
    "DATABASE_URL",
    "postgresql+psycopg://postgres:postgres123secure@localhost:5432/tradelab",
)

from tradelab_api.db.models import Bot, Strategy, StrategyGroup, StrategyVersion
from tradelab_api.db.session import (
    SessionLocal,
    apply_schema_compatibility,
    get_engine,
    verify_database_connection,
)
from tradelab_api.services.test_data_cleanup import (
    CLEANUP_ACTOR,
    CleanupGuardError,
    apply_test_data_cleanup,
    build_test_data_cleanup_plan,
)

try:
    verify_database_connection()
except RuntimeError as exc:
    pytest.skip(str(exc), allow_module_level=True)
apply_schema_compatibility()


@pytest.fixture(autouse=True)
def cleanup_pytest_rows():
    _soft_delete_pytest_cleanup_rows()
    yield
    _soft_delete_pytest_cleanup_rows()


def test_cleanup_preview_targets_test_group_tree_without_mutating() -> None:
    suffix = uuid4().hex[:8]
    with SessionLocal(bind=get_engine()) as session:
        fixture = _create_strategy_tree(
            session,
            slug=f"test-group-preview-{suffix}",
            metadata={"visibility": "test", "purpose": "automated_test_fixture"},
            description="Integration test group",
        )
        user_group = _create_group(
            session,
            slug=f"user-group-preview-{suffix}",
            metadata={},
            description="User research group",
        )
        session.commit()

        summary = build_test_data_cleanup_plan(session)

        assert summary.mode == "preview"
        assert summary.group_count >= 1
        assert summary.strategy_count >= 1
        assert summary.version_count >= 1
        assert summary.bot_count >= 1
        assert fixture["group_id"] in summary.group_ids
        assert fixture["strategy_id"] in summary.strategy_ids
        assert fixture["version_id"] in summary.version_ids
        assert fixture["bot_id"] in summary.bot_ids
        assert user_group.id not in summary.group_ids

        session.expire_all()
        assert session.get(StrategyGroup, fixture["group_id"]).is_deleted is False
        assert session.get(Strategy, fixture["strategy_id"]).is_deleted is False
        assert session.get(StrategyVersion, fixture["version_id"]).is_deleted is False
        assert session.get(Bot, fixture["bot_id"]).is_deleted is False


def test_cleanup_apply_soft_deletes_target_tree_and_is_idempotent() -> None:
    suffix = uuid4().hex[:8]
    with SessionLocal(bind=get_engine()) as session:
        _create_group(
            session,
            slug=f"user-group-apply-{suffix}",
            metadata={"visibility": "private"},
            description="User-owned strategy group",
        )
        fixture = _create_strategy_tree(
            session,
            slug=f"test-group-apply-{suffix}",
            metadata={"visibility": "test", "purpose": "automated_test_fixture"},
            description="Integration test group",
        )
        session.commit()

        first = apply_test_data_cleanup(session, updated_by=CLEANUP_ACTOR)
        session.commit()
        session.expire_all()

        assert first.mode == "apply"
        assert fixture["group_id"] in first.group_ids
        assert session.get(StrategyGroup, fixture["group_id"]).is_deleted is True
        assert session.get(StrategyGroup, fixture["group_id"]).is_active is False
        assert session.get(Strategy, fixture["strategy_id"]).is_deleted is True
        assert session.get(StrategyVersion, fixture["version_id"]).is_deleted is True
        assert session.get(Bot, fixture["bot_id"]).is_deleted is True
        assert session.get(StrategyGroup, fixture["group_id"]).updated_by == CLEANUP_ACTOR

        second = apply_test_data_cleanup(session, updated_by=CLEANUP_ACTOR)
        session.commit()

        assert second.group_count == 0
        assert second.strategy_count == 0
        assert second.version_count == 0
        assert second.bot_count == 0


def test_cleanup_selector_includes_legacy_test_patterns_and_skips_user_groups() -> None:
    suffix = uuid4().hex[:8]
    with SessionLocal(bind=get_engine()) as session:
        slug_pattern = _create_group(
            session,
            slug=f"test-group-legacy-{suffix}",
            metadata={},
            description="Generated by automated test",
        )
        description_pattern = _create_group(
            session,
            slug=f"group-legacy-{suffix}",
            metadata={},
            description="Integration test group",
        )
        metadata_pattern = _create_group(
            session,
            slug=f"purpose-legacy-{suffix}",
            metadata={"purpose": "automated_test_fixture"},
            description="Generated fixture",
        )
        user_group = _create_group(
            session,
            slug=f"user-group-legacy-{suffix}",
            metadata={},
            description="User research group",
        )
        session.commit()

        summary = build_test_data_cleanup_plan(session)

        assert slug_pattern.id in summary.group_ids
        assert description_pattern.id in summary.group_ids
        assert metadata_pattern.id in summary.group_ids
        assert user_group.id not in summary.group_ids


def test_cleanup_guard_rejects_baseline_and_workbench_targets() -> None:
    suffix = uuid4().hex[:8]
    with SessionLocal(bind=get_engine()) as session:
        baseline_like = _create_group(
            session,
            slug=f"test-group-baseline-guard-{suffix}",
            metadata={
                "visibility": "test",
                "purpose": "automated_test_fixture",
                "isBaseline": True,
            },
            description="Integration test group",
        )
        workbench_like = _create_group(
            session,
            slug=f"test-group-workbench-guard-{suffix}",
            metadata={
                "visibility": "workbench",
                "purpose": "automated_test_fixture",
            },
            description="Integration test group",
        )
        session.commit()

        with pytest.raises(CleanupGuardError) as baseline_error:
            build_test_data_cleanup_plan(session)
        assert str(baseline_like.id) in str(baseline_error.value)
        assert "baseline" in str(baseline_error.value).lower()

        baseline_like.metadata_ = {"visibility": "test", "purpose": "automated_test_fixture"}
        session.flush()

        with pytest.raises(CleanupGuardError) as workbench_error:
            build_test_data_cleanup_plan(session)
        assert str(workbench_like.id) in str(workbench_error.value)
        assert "workbench" in str(workbench_error.value).lower()


def test_cleanup_cli_preview_outputs_json_without_commit(monkeypatch, capsys) -> None:
    from tradelab_api.tools import cleanup_test_data

    class FakeSession:
        committed = False
        rolled_back = False
        closed = False

        def commit(self):
            self.committed = True

        def rollback(self):
            self.rolled_back = True

        def close(self):
            self.closed = True

    fake_session = FakeSession()
    monkeypatch.setattr(cleanup_test_data, "get_engine", lambda: object())
    monkeypatch.setattr(cleanup_test_data, "SessionLocal", lambda bind=None: fake_session)
    monkeypatch.setattr(
        cleanup_test_data,
        "build_test_data_cleanup_plan",
        lambda session: cleanup_test_data.TestDataCleanupSummary(mode="preview"),
    )

    exit_code = cleanup_test_data.main([])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert '"mode": "preview"' in captured.out
    assert fake_session.committed is False
    assert fake_session.rolled_back is False
    assert fake_session.closed is True


def test_cleanup_cli_apply_commits_and_uses_actor(monkeypatch, capsys) -> None:
    from tradelab_api.tools import cleanup_test_data

    class FakeSession:
        committed = False
        rolled_back = False

        def commit(self):
            self.committed = True

        def rollback(self):
            self.rolled_back = True

        def close(self):
            pass

    fake_session = FakeSession()
    received: dict[str, str] = {}

    def fake_apply(session, *, updated_by: str):
        received["updated_by"] = updated_by
        return cleanup_test_data.TestDataCleanupSummary(mode="apply")

    monkeypatch.setattr(cleanup_test_data, "get_engine", lambda: object())
    monkeypatch.setattr(cleanup_test_data, "SessionLocal", lambda bind=None: fake_session)
    monkeypatch.setattr(cleanup_test_data, "apply_test_data_cleanup", fake_apply)

    exit_code = cleanup_test_data.main(["--apply", "--updated-by", "pytest-cli"])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert '"mode": "apply"' in captured.out
    assert received["updated_by"] == "pytest-cli"
    assert fake_session.committed is True
    assert fake_session.rolled_back is False


def _create_group(
    session,
    *,
    slug: str,
    metadata: dict[str, object],
    description: str,
) -> StrategyGroup:
    group = StrategyGroup(
        name=f"Cleanup {slug}",
        slug=slug,
        description=description,
        metadata_=metadata,
        created_by="pytest-cleanup",
    )
    session.add(group)
    session.flush()
    session.refresh(group)
    return group


def _soft_delete_pytest_cleanup_rows() -> None:
    with SessionLocal(bind=get_engine()) as session:
        for model in (Bot, StrategyVersion, Strategy, StrategyGroup):
            rows = session.query(model).filter(model.created_by == "pytest-cleanup").all()
            for row in rows:
                row.is_active = False
                row.is_deleted = True
                row.updated_by = "pytest-cleanup-fixture"
        session.commit()


def _create_strategy_tree(
    session,
    *,
    slug: str,
    metadata: dict[str, object],
    description: str,
) -> dict[str, UUID]:
    group = _create_group(session, slug=slug, metadata=metadata, description=description)
    strategy = Strategy(
        strategy_group_id=group.id,
        name=f"Strategy {slug}",
        slug=f"strategy-{slug}",
        description="Automated cleanup test strategy",
        status="active",
        runtime_config={},
        risk_config={},
        metadata_=dict(metadata),
        created_by="pytest-cleanup",
    )
    session.add(strategy)
    session.flush()
    version = StrategyVersion(
        strategy_id=strategy.id,
        version_number=1,
        source_code="def on_candle(ctx):\n    return None\n",
        source_hash=f"hash-{slug}",
        validation_status="valid",
        validation_message=None,
        created_by="pytest-cleanup",
    )
    session.add(version)
    session.flush()
    strategy.current_version_id = version.id
    bot = Bot(
        strategy_id=strategy.id,
        strategy_version_id=version.id,
        name=f"Bot {slug}",
        mode="backtest",
        status="draft",
        symbol="BTCUSDT",
        timeframe="1h",
        runtime_config={},
        risk_config={},
        metadata_=dict(metadata),
        created_by="pytest-cleanup",
    )
    session.add(bot)
    session.flush()
    return {
        "group_id": group.id,
        "strategy_id": strategy.id,
        "version_id": version.id,
        "bot_id": bot.id,
    }
