// <auto-generated />
using System;
using Blocks.AiVideoService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blocks.AiVideoService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AiVideoDbContext))]
    partial class AiVideoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blocks.AiVideoService.Domain.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("locator");

                    b.Property<string>("LogicalType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logical_type");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("run_id");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_key");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_key");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_key");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex(new[] { "RunId" }, "ix_artifact_run_id");

                    b.HasIndex(new[] { "SourceKey", "RunId", "Locator", "Checksum" }, "ux_artifact_source_run_locator_checksum")
                        .IsUnique();

                    b.ToTable("artifact", null, t =>
                        {
                            t.HasCheckConstraint("CK_Artifact_Confidence", "confidence IN ('verified', 'metadata-only', 'absent', 'Unknown')");

                            t.HasCheckConstraint("CK_Artifact_StageKey", "stage_key IN ('collect-news', 'build-weekly-corpus', 'score-select-stories', 'derive-angles', 'build-episode-package', 'build-visual-assets', 'generate-narration', 'compile-render-video', 'qa-review-delivery')");
                        });
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applied");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_key");

                    b.HasKey("Id");

                    b.ToTable("import_batch", (string)null);
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.ImportedRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_version");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lane");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_key");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("window_start");

                    b.Property<string>("WorkflowVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workflow_version");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ImportBatchId" }, "ix_imported_run_import_batch_id");

                    b.HasIndex(new[] { "SourceKey" }, "ix_imported_run_source_key");

                    b.ToTable("imported_run", (string)null);
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("locator");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("run_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_key");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_key");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex(new[] { "RunId" }, "ix_receipt_run_id");

                    b.HasIndex(new[] { "SourceKey", "RunId", "Locator", "Checksum" }, "ux_receipt_source_run_locator_checksum")
                        .IsUnique();

                    b.ToTable("receipt", null, t =>
                        {
                            t.HasCheckConstraint("CK_Receipt_Confidence", "confidence IN ('verified', 'metadata-only', 'absent', 'Unknown')");

                            t.HasCheckConstraint("CK_Receipt_StageKey", "stage_key IN ('collect-news', 'build-weekly-corpus', 'score-select-stories', 'derive-angles', 'build-episode-package', 'build-visual-assets', 'generate-narration', 'compile-render-video', 'qa-review-delivery')");
                        });
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.ReconciliationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("conflict_type");

                    b.Property<string>("ExpectedChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_checksum");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("locator");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("ObservedChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("observed_checksum");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("run_id");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_key");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex(new[] { "RunId" }, "ix_reconciliation_event_run_id");

                    b.ToTable("reconciliation_event", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReconciliationEvent_StageKey", "stage_key IN ('collect-news', 'build-weekly-corpus', 'score-select-stories', 'derive-angles', 'build-episode-package', 'build-visual-assets', 'generate-narration', 'compile-render-video', 'qa-review-delivery')");
                        });
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.StageAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttemptId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("attempt_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("run_id");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_key");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex(new[] { "AttemptId" }, "ix_stage_attempt_attempt_id");

                    b.HasIndex(new[] { "RunId" }, "ix_stage_attempt_run_id");

                    b.ToTable("stage_attempt", null, t =>
                        {
                            t.HasCheckConstraint("CK_StageAttempt_StageKey", "stage_key IN ('collect-news', 'build-weekly-corpus', 'score-select-stories', 'derive-angles', 'build-episode-package', 'build-visual-assets', 'generate-narration', 'compile-render-video', 'qa-review-delivery')");
                        });
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.Artifact", b =>
                {
                    b.HasOne("Blocks.AiVideoService.Domain.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artifact_import_batch");
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.ImportedRun", b =>
                {
                    b.HasOne("Blocks.AiVideoService.Domain.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imported_run_import_batch");
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.Receipt", b =>
                {
                    b.HasOne("Blocks.AiVideoService.Domain.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_import_batch");
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.ReconciliationEvent", b =>
                {
                    b.HasOne("Blocks.AiVideoService.Domain.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reconciliation_event_import_batch");
                });

            modelBuilder.Entity("Blocks.AiVideoService.Domain.StageAttempt", b =>
                {
                    b.HasOne("Blocks.AiVideoService.Domain.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stage_attempt_import_batch");
                });
#pragma warning restore 612, 618
        }
    }
}
