import {
  Activity,
  Blocks,
  Bot,
  Database,
  FileArchive,
  FolderKanban,
  Gauge,
  History,
  LayoutGrid,
  ListTree,
  Plug,
  ScrollText,
  Settings,
  ShieldCheck,
  UserRound,
  UsersRound,
} from "lucide-react"

import type { NavNode } from "./types"

export const navigationFixture: NavNode[] = [
  {
    id: "overview",
    title: "Overview",
    kind: "group",
    owner: "system",
    ownerKey: "blocks-web",
    sort: 10,
    isVisible: true,
    status: "active",
    children: [
      {
        id: "workspace",
        title: "Workspace",
        kind: "subgroup",
        parentId: "overview",
        owner: "system",
        ownerKey: "blocks-web",
        icon: Gauge,
        sort: 10,
        isVisible: true,
        status: "active",
        children: [
          {
            id: "platform-overview",
            title: "Platform Overview",
            kind: "menu",
            parentId: "workspace",
            route: "/",
            owner: "system",
            ownerKey: "blocks-web",
            sort: 10,
            capability: "view",
            isVisible: true,
            status: "active",
          },
          {
            id: "service-health",
            title: "Service Health",
            kind: "menu",
            parentId: "workspace",
            route: "/overview/service-health",
            owner: "system",
            ownerKey: "blocks-web",
            sort: 20,
            capability: "view",
            isVisible: true,
            status: "active",
          },
          {
            id: "recent-activity",
            title: "Recent Activity",
            kind: "menu",
            parentId: "workspace",
            route: "/overview/recent-activity",
            owner: "system",
            ownerKey: "blocks-web",
            sort: 30,
            capability: "view",
            isVisible: true,
            status: "active",
          },
        ],
      },
    ],
  },
  {
    id: "system",
    title: "System",
    kind: "group",
    owner: "system",
    ownerKey: "system-service",
    sort: 20,
    isVisible: true,
    status: "active",
    children: [
      {
        id: "system-core",
        title: "System Core",
        kind: "subgroup",
        parentId: "system",
        owner: "system",
        ownerKey: "system-service",
        icon: Blocks,
        sort: 10,
        isVisible: true,
        status: "active",
        children: [
          {
            id: "system-overview",
            title: "System Overview",
            kind: "menu",
            parentId: "system-core",
            route: "/system/overview",
            owner: "system",
            ownerKey: "system-service",
            sort: 10,
            capability: "view",
            isVisible: true,
            status: "active",
          },
          {
            id: "audit-log",
            title: "Audit Log",
            kind: "menu",
            parentId: "system-core",
            route: "/system/audit-log",
            owner: "system",
            ownerKey: "system-service",
            sort: 20,
            capability: "view",
            isVisible: true,
            status: "active",
          },
        ],
      },
      {
        id: "identity",
        title: "Identity",
        kind: "subgroup",
        parentId: "system",
        owner: "system",
        ownerKey: "system-service",
        icon: ShieldCheck,
        sort: 20,
        isVisible: true,
        status: "active",
        children: [
          {
            id: "users",
            title: "Users",
            kind: "menu",
            parentId: "identity",
            route: "/system/identity/users",
            owner: "system",
            ownerKey: "system-service",
            icon: UserRound,
            sort: 10,
            capability: "view",
            isVisible: true,
            status: "active",
          },
          {
            id: "roles",
            title: "Roles",
            kind: "menu",
            parentId: "identity",
            route: "/system/identity/roles",
            owner: "system",
            ownerKey: "system-service",
            icon: UsersRound,
            sort: 20,
            capability: "view",
            isVisible: true,
            status: "active",
          },
          {
            id: "menus",
            title: "Menus",
            kind: "menu",
            parentId: "identity",
            route: "/system/identity/menus",
            owner: "system",
            ownerKey: "system-service",
            icon: ListTree,
            sort: 30,
            capability: "view",
            isVisible: true,
            status: "active",
          },
          {
            id: "system-groups",
            title: "System Groups",
            kind: "menu",
            parentId: "identity",
            route: "/system/identity/system-groups",
            owner: "system",
            ownerKey: "system-service",
            icon: LayoutGrid,
            sort: 35,
            capability: "view",
            isVisible: true,
            status: "active",
          },

        ],
      },
    ],
  },
  {
    id: "services",
    title: "Services",
    kind: "group",
    owner: "service",
    ownerKey: "blocks",
    sort: 30,
    isVisible: true,
    status: "active",
    children: [
      {
        id: "file-service",
        title: "File Service",
        kind: "subgroup",
        parentId: "services",
        owner: "service",
        ownerKey: "file-service",
        icon: FolderKanban,
        sort: 10,
        isVisible: true,
        status: "active",
        children: [
          {
            id: "file-library",
            title: "Library",
            kind: "menu",
            parentId: "file-service",
            route: "/services/files/library",
            owner: "service",
            ownerKey: "file-service",
            icon: FileArchive,
            sort: 10,
            capability: "view",
            isVisible: true,
            status: "active",
          },
          {
            id: "storage-providers",
            title: "Storage Providers",
            kind: "menu",
            parentId: "file-service",
            route: "/services/files/storage-providers",
            owner: "service",
            ownerKey: "file-service",
            icon: Settings,
            sort: 20,
            capability: "view",
            isVisible: true,
            status: "active",
          },
        ],
      },
    ],
  },
  {
    id: "plugins",
    title: "Plugins",
    kind: "group",
    owner: "plugin",
    ownerKey: "plugin-runtime",
    sort: 40,
    isVisible: true,
    status: "active",
    children: [
      {
        id: "plugin-launchpad",
        title: "Plugin Launchpad",
        kind: "subgroup",
        parentId: "plugins",
        owner: "plugin",
        ownerKey: "plugin-runtime",
        icon: Plug,
        sort: 10,
        isVisible: true,
        status: "draft",
        children: [
          {
            id: "installed-plugins",
            title: "Installed Plugins",
            kind: "menu",
            parentId: "plugin-launchpad",
            route: "/plugins/installed",
            owner: "plugin",
            ownerKey: "plugin-runtime",
            icon: LayoutGrid,
            sort: 10,
            capability: "view",
            isVisible: true,
            status: "draft",
          },
          {
            id: "plugin-activity",
            title: "Plugin Activity",
            kind: "menu",
            parentId: "plugin-launchpad",
            route: "/plugins/activity",
            owner: "plugin",
            ownerKey: "plugin-runtime",
            icon: Activity,
            sort: 20,
            capability: "view",
            isVisible: true,
            status: "draft",
          },
          {
            id: "plugin-manifests",
            title: "Manifests",
            kind: "menu",
            parentId: "plugin-launchpad",
            route: "/plugins/manifests",
            owner: "plugin",
            ownerKey: "plugin-runtime",
            icon: ScrollText,
            sort: 30,
            capability: "view",
            isVisible: true,
            status: "draft",
          },
        ],
      },
      {
        id: "trade-lab",
        title: "TradeLab",
        kind: "subgroup",
        parentId: "plugins",
        owner: "plugin",
        ownerKey: "tradelab",
        icon: Bot,
        sort: 20,
        isVisible: true,
        status: "active",
        children: [
          {
            id: "trade-lab-strategy-lab",
            title: "Strategy Lab",
            kind: "menu",
            parentId: "trade-lab",
            route: "/plugins/tradelab",
            owner: "plugin",
            ownerKey: "tradelab",
            icon: Bot,
            sort: 10,
            capability: "analyze",
            isVisible: true,
            status: "active",
          },
          {
            id: "trade-lab-datasets",
            title: "Datasets",
            kind: "menu",
            parentId: "trade-lab",
            route: "/plugins/tradelab/datasets",
            owner: "plugin",
            ownerKey: "tradelab",
            icon: Database,
            sort: 20,
            capability: "analyze",
            isVisible: true,
            status: "active",
          },
        ],
      },
      {
        id: "ai-video-production",
        title: "AI Video Production",
        kind: "subgroup",
        parentId: "plugins",
        owner: "plugin",
        ownerKey: "ai-video-production",
        icon: Bot,
        sort: 30,
        isVisible: true,
        status: "active",
        children: [
          {
            id: "ai-video-runs",
            title: "Runs",
            kind: "menu",
            parentId: "ai-video-production",
            route: "/plugins/ai-video",
            owner: "plugin",
            ownerKey: "ai-video-production",
            icon: Bot,
            sort: 10,
            capability: "view",
            isVisible: true,
            status: "active",
          },
        ],
      },
    ],
  },
]

export const recentActivityIcon = History
