<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Blocks.SystemService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.76.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.76.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Stax.AutoDependencyInjectionRegistration" Version="4.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\system.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\audit.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Infrastructure\Data\Migrations\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\platform\service-defaults\Blocks.ServiceDefaults\Blocks.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\platform\shared\Blocks.Shared\Blocks.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\file-service\Blocks.FileService\Protos\file.proto" GrpcServices="Client"
      Link="Protos\file.proto" />
  </ItemGroup>
</Project>
